receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ logging, jaeger ]
      processors: [ batch]
    metrics:
      receivers: [ otlp]
      exporters: [ logging ]
      processors: [ batch]
    logs:
      receivers: [ otlp ]
      exporters: [ logging ]